//removed generateAbout from module code
const generateProjects = projectsArr => {
  return `
  ${projectsArr
  .filter(({ feature }) => !feature)
  .map(({ name, description, languages, link, installation, contribution, test, usage, email }) => {
    return `

![NPM](https://img.shields.io/npm/l/inquirer?style=plastic)

# Project Name:  ${name}

## Table of Contents
* [Project Description](#Project%20Description:)   
* [Installation](#Installation)
* [Usage Instructions](#Usage%20Instructions)
* [Contributing](#Contributing)   
* [Testing](#Testing)
* [GitHub Repository Link](#GitHub%20Repository%20Link:)
* [Lanugages Used](#Languages%20Used:)   

## Project Description: 
* ${description}

## Installation 
* ${installation}

## Usage Instructions 
* ${usage}

## Contributing 
* ${contribution}
* If your issues, pull requests, or other GitHub problems are not being resolves, please reach out to me at ${email}. 

## Testing
* ${test}

## GitHub Repository Link:
* ${link}

## Languages Used:
* ${languages.join(', ')}
    `
    })
    .join('')}
    `;
  };
  

    module.exports = templateData => {
      // destructure page data by section
      const { projects, about, ...header } = templateData;
      return `
## ${generateProjects(projects)}

## Questions?
### Direct them to (github.com/${header.github})



#### README generated in ${new Date().getFullYear()}
#### This README was generated by: ${header.name}
      `;
    };